// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataPractice.Models
{
    public partial class items
    {
        public items()
        {
            SalesSubs = new HashSet<SalesSubs>();
        }

        [Key]
        public int ItemID { get; set; }
        [StringLength(50)]
        public string ItemName { get; set; }
        public double ItemRate { get; set; }

        [InverseProperty("Item")]
        public virtual ICollection<SalesSubs> SalesSubs { get; set; }
    }
}