// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataPractice.Models
{
    public partial class SalesMains
    {
        public SalesMains()
        {
            SalesSubs = new HashSet<SalesSubs>();
        }

        [Key]
        public int SalesMainID { get; set; }
        public DateTime SalesDate { get; set; }
        public double TotalAmount { get; set; }

        [InverseProperty("SalesMain")]
        public virtual ICollection<SalesSubs> SalesSubs { get; set; }
    }
}